image: node

cache:
  paths:
    - node_modules/

pages:
  script:
    - npm install
    - npm run build
    - npm run export
    - mv public public2
    - mkdir public
    - mv out/* public
  artifacts:
    paths:
      - public
  only:
    - master
